name: Cpplint

on: [ pull_request ]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        name: Checkout
      - uses: reviewdog/action-cpplint@master
        name: Run cpplint
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          filter: "-build/include
              ,-runtime/int
              ,-build/include_subdir
              ,-legal/copyright
              ,-build/c++20
              ,-build/c++11
              "
